# Setup
title:               'The League of Robot Runners Virtual Expo 2024'
tagline:             'May 20th, from 1530 EST (UTC-5)'
description:         ''
url:                 https://expo24.leagueofrobotrunners.org
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-admin
  - rack
  - rackup
  # - jekyll-coffeescript
  # - jekyll-assets
  # - another-jekyll-plugin

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
