# Setup
title:               'The League of Robot Runners Virtual Expo 2025'
tagline:             'June 2nd, from 8 am EDT (UTC-4)'
description:         ''
# url:                 https://expo25.leagueofrobotrunners.org
url:                 https://mapf-competition.github.io
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-admin
  - rack
  - rackup
  # - jekyll-coffeescript
  # - jekyll-assets
  # - another-jekyll-plugin

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
